# Configuration Constants
TIMEFRAMES = {
    "4H": 240,   
    "15M": 15, 
    "30M":30    
}
PIP_VALUE = 0.0001  
RISK_PERCENTAGE = 1  
REWARD_TO_RISK_RATIO = 2  
DEFAULT_BUFFER_PIPS = 10  
EXOTIC_PAIRS = ["USD/TRY", "EUR/ZAR"] 
HIGH_RISK_RATIO = 3  
LOW_RISK_RATIO = 2   
ATR_PERIOD = 14
RISK_PERCENTAGE = 0.02
HIGH_RISK_RATIO = 3
SAFE_ZONE_MULTIPLIER = 0.5
MOVING_AVERAGES = [7, 14, 89, 200]
RSI_PERIOD = 14  
ADX_THRESHOLD = 20 
